### ISSUE TITLE
Woof is too far left

### ISSUE THREAD

**Issue by TuPpKaM** [johanwulf/johanwulf.github.io#1]
The Woof when pressing the icon appears very far away, on the left side.
![chrome_2023-01-18_19-12-30](https://user-images.githubusercontent.com/42248511/213261416-47894b2a-f39c-4159-aab3-b26c21212a33.png)

**Comment by johanwulf** [comment]
Thank you for the bug report. Next time, please use the following template:

**Bug Description:**

[Insert hilarious, over-the-top description of the bug here. For example: "The program keeps randomly turning my computer into a toaster. I can't even make toast properly anymore!"]

**Steps to Reproduce:**

1. [Insert ridiculous and unlikely steps that somehow lead to the bug occurring. For example: "Start the program while wearing a clown nose and simultaneously eating a burrito with one hand and playing the accordion with the other"]
2. [Insert more ridiculous steps here]
3. [Insert even more ridiculous steps here, until you feel like the reader will have a good laugh]

**Expected Results:**

[Insert something completely unrelated to the bug, but still funny. For example: "I expected to be able to make toast without my computer catching on fire."]

**Actual Results:**

[Insert something even more ridiculous and funny than the expected results. For example: "My computer turned into a giant robot and started dancing the cha-cha."]

**Notes:**

[Insert any additional information or jokes here. For example: "I've attached a video of the robot dance as proof. Also, my cat seems to really enjoy the robot dance, so please keep that in mind when fixing this bug."]
